env:
  browser: true
  es2021: true
extends: airbnb
parserOptions:
  ecmaVersion: latest
  sourceType: module
rules:
  react/function-component-definition: [2, { "namedComponents": "arrow-function" }]
  react/prop-types: 0
  react/jsx-props-no-spreading: 0
  no-unused-vars: 1
